spring:
  application:
    name: video
  config:
    import: file:env.properties
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 8081

video:
  folder: videos/
